export async function generateStaticParams() {
  // All chemical product slugs from locale files
  const chemicalSlugs = [
    'naphtha',
    'propylene-propene',
    'benzene',
    'red-phosphorus',
    'trimethyl-phosphite-tmpi',
    'triphenyl-phosphite-tppi',
    'triethyl-phosphite-tepi',
    'diethyl-phosphite-depi',
    'dimethyl-phosphite-dmpi',
    'dimethyl-methylphosphonate-dmmp',
    'carbon-disulfide-cs2',
    'sodium-sulfide-na2s',
    'methyl-tertiary-butyl-ether-mtbe',
    'sulfur',
    'etbe',
    'pta',
    'meg',
    'px',
    'ox',
    'toluene',
    'cyclohexane',
    'antioxidant-1010',
    'antioxidant-1076',
    'antioxidant-168',
    'antioxidant-1098',
    'antioxidant-l135',
    'antioxidant-1135',
    'antioxidant-1315',
    'antioxidant-blend-168-1010',
    'potassium-bicarbonate',
    'mixed-hexenes',
    'tert-butylamine',
    'methanol',
    'isobutylene',
    'ptbba',
    'ptbmb',
    'isohexane',
    'toa',
    'tba',
    'naamps',
    'atbs',
    '4-butylaniline',
    'c10-aromatic-solvent',
    '3-phenylpentane',
    'tertiary-amyl-benzene',
    'secondary-butyl-benzene',
    'normal-butyl-benzene',
    'isobutyl-benzene',
    'zddp-md',
    'zddp-im',
    'phosphorus-pentoxide',
    'hp-mtbe',
    'sodium-cyanide',
    'cyanuric-chloride',
    'ethylenediamine',
    'piperazine',
    'ortho-tert-butyl-phenol-otbp',
    'osbp',
    'osbp-detailed',
    '2-6-di-sec-butyl-phenol-2-6-dsbp',
    'polybutadiene-rubber-pbr',
    'styrene-butadiene-rubber-sbr',
    'polyvinyl-chloride-pvc',
    'polyethylene-pe',
    'polypropylene-pp',
    'polyester-staple-fiber-psf',
    'polyester-filament-yarn-pfy',
    'polyethylene-terephthalate-pet',
    // New chemicals from brochure - Phosphorus Based
    'tributyl-phosphate-tbp',
    // New chemicals from brochure - Alkanolamines Group
    'diethylenetriamine-deta',
    'aminoethyl-ethanolamine-aeea',
    'aminoethyl-piperazine-aep',
    'triisopropanolamine-tipa',
    'monoethanolamine-mea',
    'diethanolamine-dea',
    'triethanolamine-tea',
    'methyl-monoethanolamine-mmea',
    'methyl-diethanolamine-mdea',
    'di-methyl-ethanolamine-dmea',
    'di-ethyl-ethanolamine-deea',
    'ethyl-monoethanolamine-emea',
    'ethyl-diethanolamine-edea',
    '2-phenoxy-ethanol',
    'diethanol-isopropanolamine-deipa',
    'n-2-hydroxy-ethyl-pyrrolidine',
    // New chemicals from brochure - Bromine Derivatives
    'calcium-bromide',
    'calcium-bromide-powder',
    'sodium-bromide',
    'zinc-bromide',
    'hydrobromic-acid',
    'diphenyl-oxide',
    // Demulsifiers & Emulsifiers
    'custom-demulsifiers',
    'custom-emulsifiers',
    'rd-support',
    // New chemicals from brochure - Phenols
    'para-tertiary-butyl-phenol-ptbp',
    '2-4-di-tertiary-butyl-phenol',
    '2-6-di-tertiary-butyl-phenol',
    // New chemicals from brochure - Aliphatic & Benzyl
    'n-benzyl-ethanolamine'
  ];

  return chemicalSlugs.map((slug) => ({ slug }));
} 