import type { Metadata } from "next";
import "./globals.css";
import { NavbarVisibilityProvider } from "../context/NavbarVisibilityContext";
import AnimatedNavbar from "../components/AnimatedNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <NavbarVisibilityProvider>
          {children}
          <AnimatedNavbar />
        </NavbarVisibilityProvider>
      </body>
    </html>
  );
}
